### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by orefalo** [KeenMate/svelte-treeview#19]
Hi,

For some reasons I can't get this project to run properly.

I mean I do get the "npm run dev" up, but what I see seems half cooked in view of code features.

am I missing something?

**Comment by ZelvaMan** [comment]
Hello,
this project is mainly a package,that  we use in other project. `npm run dev` is primarily used during the development.
If you want to use it, install `@keenmate/svelte-treeview` using your favourite package manager (npm)
(Note, that font awesome is required for displaying icons).

We recently release version 1.0.0 of this package, so documentation and demo is still work in progress.
For now I suggest looking at comments in Treeview.svelte file.

**Comment by orefalo** [comment]
thank you
