### ISSUE TITLE
drag and drop?

### ISSUE THREAD

**Issue by orefalo** [KeenMate/svelte-treeview#20]
Would you have a DnD sample example?

**Comment by ZelvaMan** [comment]
Hello,
Drag and drop example example will be available in near future.

**Comment by orefalo** [comment]
ty.
it's hard to find a decent treeview in svelte...

**Comment by ZelvaMan** [comment]
@orefalo btw how will you been using the drag and drop feature? Will you be computing new tree in client, or on server?

**Comment by orefalo** [comment]
Client side.

What a weird question.
An I missing anything?
